AWSTemplateFormatVersion: "2010-09-09"
Description: "Majin Analytics - API Gateway and Lambda Integration"

Parameters:
  ProjectName:
    Type: String
    Default: majin-analytics
  CognitoUserPoolArn:
    Type: String
    Default: "arn:aws:cognito-idp:ap-northeast-1:590184009554:userpool/ap-northeast-1_rgS1rEHRB"
  DataBucketName:
    Type: String
  JobTableName:
    Type: String
  LambdaRoleArn:
    Type: String
  AIModelId:
    Type: String
    Default: "anthropic.claude-3-5-sonnet-20240620-v1:0"
  AllowedIpRange:
    Type: String
    Default: "0.0.0.0/0"
    Description: "Allowed IP range for external API access (CIDR format). Use 0.0.0.0/0 to allow all."
  ApiKey:
    Type: String
    NoEcho: true
    Default: "majin-secret-key-2024"
    Description: "API Key for external system access."

Resources:
  # --- API Gateway (HTTP API) ---
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ${ProjectName}-api
      ProtocolType: HTTP
      CorsConfiguration:
        AllowHeaders: ["Content-Type", "Authorization"]
        AllowMethods: ["GET", "POST", "OPTIONS"]
        AllowOrigins: ["*"]

  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: "$default"
      AutoDeploy: true

  # --- Lambda Functions ---

  DispatcherFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-dispatcher
      Handler: dispatcher.handler
      Runtime: python3.12
      Role: !Ref LambdaRoleArn
      Code:
        ZipFile: "def handler(event, context): return {'statusCode': 200}"
      Environment:
        Variables:
          DATA_BUCKET: !Ref DataBucketName
          JOB_TABLE: !Ref JobTableName
          PROCESS_FUNCTION: !Sub ${ProjectName}-processor
          ALLOWED_IP_RANGE: !Ref AllowedIpRange
          API_KEY: !Ref ApiKey

  StatusFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-status
      Handler: status.handler
      Runtime: python3.12
      Role: !Ref LambdaRoleArn
      Code:
        ZipFile: "def handler(event, context): return {'statusCode': 200}"
      Environment:
        Variables:
          JOB_TABLE: !Ref JobTableName
          DATA_BUCKET: !Ref DataBucketName
          ALLOWED_IP_RANGE: !Ref AllowedIpRange
          API_KEY: !Ref ApiKey

  ProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-processor
      Handler: processor.handler
      Runtime: python3.12
      Role: !Ref LambdaRoleArn
      Code:
        ZipFile: "def handler(event, context): return {'statusCode': 200}"
      Timeout: 300 # 5 minutes for AI analysis
      MemorySize: 1024
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:14
      Environment:
        Variables:
          DATA_BUCKET: !Ref DataBucketName
          JOB_TABLE: !Ref JobTableName
          MODEL_ID: !Ref AIModelId

  # --- API Integrations ---

  DispatcherIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt DispatcherFunction.Arn
      PayloadFormatVersion: "2.0"

  StatusIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt StatusFunction.Arn
      PayloadFormatVersion: "2.0"

  # --- API Routes ---

  AnalyzeRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /analyze"
      Target: !Sub integrations/${DispatcherIntegration}

  StatusRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /jobs/{id}"
      Target: !Sub integrations/${StatusIntegration}

  # --- Permissions ---

  DispatcherPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DispatcherFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*

  StatusPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref StatusFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*

  # S3 Trigger for Processor
  S3ProcessorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProcessorFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${DataBucketName}

Outputs:
  ApiUrl:
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com
  ApiId:
    Value: !Ref HttpApi
  DispatcherFunctionName:
    Value: !Ref DispatcherFunction
  StatusFunctionName:
    Value: !Ref StatusFunction
  ProcessorFunctionName:
    Value: !Ref ProcessorFunction
  ProcessorFunctionArn:
    Value: !GetAtt ProcessorFunction.Arn
  ApiEndpoint:
    Value: !GetAtt HttpApi.ApiEndpoint
